version: "3.9"
services:
  app:
    working_dir: /app
    command: sh -c "npm install && npx nodemon app.mjs"
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 127.0.0.1:5903:3000

  proxy:
    image: node:20.8.1-alpine3.17
    command: sh -c "npx localtunnel --port 3000 --local-host app --subdomain etwas-gelungenes-${USER}"
